### ISSUE TITLE
 styles are damaged

### ISSUE THREAD

**Issue by EDcasa** [logisticinfotech/ionic4-datepicker#40]
Styles are damaged when running on an ios device with ionic 4 when selecting a year or month, everything goes to the top
![sss](https://user-images.githubusercontent.com/48493967/66227058-ed7c9a00-e6a1-11e9-8a0f-6bbec6ff2290.jpeg)

**Comment by chintan13** [comment]
In which simulator have you tried this? let me know version of os also.

**Comment by EDcasa** [comment]
Version: iOS 11.0
Simulator:  iPhone 11

**Comment by EDcasa** [comment]
I have solved it by implementing the mode option in the modal creation 
mode: 'md',
so it works correctly.

**Comment by jjacobs33589** [comment]
I'm having this same problem on iOS. I'm using it as a directive as shown below. How do I set the mode to md when I'm using it as a directive instead of a component?

<img width="689" alt="Screen Shot 2020-02-10 at 4 44 47 PM" src="https://user-images.githubusercontent.com/8160113/74200734-f0296600-4c24-11ea-8c4d-0187a5c5265c.png">

**Comment by EDcasa** [comment]
Check this.
![Captura de pantalla de 2020-02-17 09-52-30](https://user-images.githubusercontent.com/48493967/74664304-77b62e00-516b-11ea-9d0b-398f538332c5.png)

**Comment by jjacobs33589** [comment]
That works! thank you!
